CREATE TABLE Player(
    PlayerID INTEGER AUTO_INCREMENT,
    Name VARCHAR(20),

    PRIMARY KEY (PlayerID)
) ENGINE=InnoDB;

CREATE TABLE ChessPiece(
  PieceID INTEGER AUTO_INCREMENT,
  Designator VARCHAR(20),
  PlayerID INTEGER,
  Position VARCHAR(2),
  PRIMARY KEY (PieceID),
  FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
) ENGINE=InnoDB;

CREATE TABLE Session(
  SessionID INTEGER AUTO_INCREMENT,
  SessionName VARCHAR(20),
  Round INTEGER,
  PlayerAID INTEGER,
  PlayerBID INTEGER,
  PRIMARY KEY (SessionID),
  FOREIGN KEY (PlayerAID) REFERENCES Player(PlayerID),
  FOREIGN KEY (PlayerBID) REFERENCES Player(PlayerID)
) ENGINE=InnoDB;